version: '3.8'

services:
  consul:
    image: consul:1.15
    container_name: consul-dev
    ports:
      - "8500:8500"       # 📊 Web UI
      - "8600:8600/udp"   # 📡 DNS çözümleme
    command: agent -dev -client=0.0.0.0
